### ISSUE TITLE
会议界面

### ISSUE THREAD

**Issue by JiahengHe** [AgoraIO-Usecase/AgoraMeeting-Android#1]
你好，请问要修改会议界面的UI在哪里能够改到呢？

**Comment by xgfd3** [comment]
在meeting-ui模块里可以修改ui，例如修改顶部栏ui，可以修改[MainTopUC](https://github.com/AgoraIO-Usecase/AgoraMeeting-Android/blob/main/libs/meeting-ui/src/main/kotlin/io/agora/meeting/ui/module/main/top/MainTopUC.kt)对应的布局文件[main_top_layout.xml](https://github.com/AgoraIO-Usecase/AgoraMeeting-Android/blob/main/libs/meeting-ui/src/main/res/layout/main_top_layout.xml)

**Comment by stephenchowxingxing** [comment]
@xgfd3 你好，这个项目会碰到 找不到 com.github.agorabuilder:native-full-sdk的问题，换成io.agora.rtc:full-sdk后还是找不到。使用的是maven { url 'https://www.jitpack.io' }
请问有解决方法吗？谢谢
